baseURL = "/"
languageCode = "en-us"
title = "USCOTS 2019: Evaluating Evidence"
theme = "hugo-initio"
publishDir = "public"

[params]
    name = "USCOTS 2019: Evaluating Evidence"
    description = "Implementing reproducible research in statistics courses using Git/Github"
    email1 = "beckman@psu.edu"
    fax1 = "814 863 1022"
    University1 = "Penn State"
    pobox1 = "323F Thomas Bldg"
    school1 = "Eberly College of Science"
    city1 = "University Park, PA 16802"
    
    email2 = "adam_sullivan@brown.edu"
    fax2 = "401 863 1980"
    University2 = "Brown University"
    pobox2 = "Box G-S121-7"
    school2 = "School of Public Health"
    city2 = "Providence, RI 02903"
    year = 2019
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"
    showSubheader = true
    showServices = false
    showRecentWorks = true
    showDownload = false
    showClients = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1


[params.disqus]
    site = ""

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = ""


[[params.social2]]
	title = "twitter"
	url = "https://twitter.com/sullivanstats"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social2]]
	title = "instagram"
	url = "https://www.instagram.com/sullivanstats"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social2]]
	title = "github"
	url = "https://github.com/sullivanstatistics"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social2]]
	title = "email"
	url = "mailto:"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
[[params.social1]]
	title = "github"
	url = "https://github.com/mdbeckman"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social1]]
	title = "email"
	url = "mailto:"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
